./sudokusolver.exe puzzles/1.txt 2
./sudokusolver.exe puzzles/2.txt 2
./sudokusolver.exe puzzles/3.txt 2
./sudokusolver.exe puzzles/4.txt 2
./sudokusolver.exe puzzles/5.txt 2
./sudokusolver.exe puzzles/6.txt 2
./sudokusolver.exe puzzles/7.txt 2
./sudokusolver.exe puzzles/8.txt 2
./sudokusolver.exe puzzles/9.txt 2
./sudokusolver.exe puzzles/10.txt 2
./sudokusolver.exe puzzles/11.txt 2
./sudokusolver.exe puzzles/12.txt 2
./sudokusolver.exe puzzles/13.txt 2
./sudokusolver.exe puzzles/14.txt 2
./sudokusolver.exe puzzles/15.txt 2
./sudokusolver.exe puzzles/16.txt 2
./sudokusolver.exe puzzles/17.txt 2
./sudokusolver.exe puzzles/18.txt 2
./sudokusolver.exe puzzles/19.txt 2
./sudokusolver.exe puzzles/20.txt 2
./sudokusolver.exe puzzles/21.txt 2
./sudokusolver.exe puzzles/22.txt 2
./sudokusolver.exe puzzles/23.txt 2
./sudokusolver.exe puzzles/24.txt 2
./sudokusolver.exe puzzles/25.txt 2
./sudokusolver.exe puzzles/26.txt 2
./sudokusolver.exe puzzles/27.txt 2
./sudokusolver.exe puzzles/28.txt 2
./sudokusolver.exe puzzles/29.txt 2
./sudokusolver.exe puzzles/30.txt 2
./sudokusolver.exe puzzles/31.txt 2
./sudokusolver.exe puzzles/32.txt 2
./sudokusolver.exe puzzles/33.txt 2
./sudokusolver.exe puzzles/34.txt 2
./sudokusolver.exe puzzles/35.txt 2
./sudokusolver.exe puzzles/36.txt 2
./sudokusolver.exe puzzles/37.txt 2
./sudokusolver.exe puzzles/38.txt 2
./sudokusolver.exe puzzles/39.txt 2
./sudokusolver.exe puzzles/40.txt 2
./sudokusolver.exe puzzles/41.txt 2
./sudokusolver.exe puzzles/42.txt 2
./sudokusolver.exe puzzles/43.txt 2
./sudokusolver.exe puzzles/44.txt 2
./sudokusolver.exe puzzles/45.txt 2
./sudokusolver.exe puzzles/46.txt 2
./sudokusolver.exe puzzles/47.txt 2
./sudokusolver.exe puzzles/48.txt 2
./sudokusolver.exe puzzles/49.txt 2
./sudokusolver.exe puzzles/50.txt 2
